listener 1883
protocol mqtt
allow_anonymous true

# WebSocket (opcional)
listener 9001
protocol websockets
allow_anonymous true

# Persistencia
persistence true
persistence_location /mosquitto/data/

# Logs
log_dest file /mosquitto/log/mosquitto.log
log_dest stdout

# Retain
retain_available true
